# configs/api.yaml
system:
  base_dir: "./"
  device: "cuda:0"
  logger:
    name: "recommender_api"
    level: "INFO"
  paths:
    log_dir: "logs/api"
    
api:
  name: "Recommendation API"
  host: "0.0.0.0"
  port: 8000
  timeout: 30.0