# configs/env/dev.yaml
debug: true
parallel_workers: 4
model_cache: false                  # 禁用模型缓存

resource:
  cpu_threads: 8
  gpu_mem_frac: 0.5                 # GPU内存限制

logging:
  level: DEBUG
  interval: 10                      # 日志刷新间隔(秒)